import './src/app/app.component.cy'
import './src/app/Components/clock/clock.component.cy'
import './src/app/Components/header/header.component.cy'
import './src/app/Components/search-bar/search-bar.component.cy'
import './src/app/Components/weather-widget-main/weather-widget-main.component.cy'